spring:
    datasource:
        url: jdbc:postgresql://localhost/?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC 
        username: root
        password: root
    jpa:
        properties:
            javax:
                persistence:
                    schema-generation:
                        create-source: metadata
                        scripts:
                            action: create
                            create-target: create.sql
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
        hibernate:
            ddl-auto: none