spring:
    datasource:
        url: ${DATABASE_URL}
    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: false
        hibernate:
            ddl-auto: none